# -*- coding: utf-8 -*-
"""práctica #2 python (bucles, Funciones y Estructuras de Datos).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rKBaSjV_i05Dv1sMEJo6Mr5zVIi8GCWV
"""

#1 ejercicio

# paso 1

horas_estudio = [2, 3, 1, 4, 2, 5, 3]

total = 0
for h in horas_estudio:
  total += h

promedio = total / len(horas_estudio)
print("Total de horas estudiadas en la semana:", total)
print("Promedio diaria:", round(promedio, 1))

# paso 2
contador = 0

for h in horas_estudio:
  if h >= 4:
    contador += 1

print("Días con 4 horas o más:", contador)

#ejercicio 2

ahorro = 0
semanas = 0

while ahorro < 300:
  ahorro += 60
  semanas += 1

print("semanas necesarias:", semanas)
print("Ahorro Final:", ahorro)

#ejercicio 3

def calcular_costo_envio(peso, distancia):
  costo = peso * 0.5 + distancia * 0.1
  return costo

resultado = calcular_costo_envio(12, 80)
print(f"Costo: {round(resultado, 2)}")


def clasificar_envio(costo):
   if costo < 10:
     return "Económico"
   elif costo < 25:
    return "Estandar"
   else:
    return "Premium"

print(clasificar_envio(resultado))

#Ejercicio 4

peliculas = ["coco", "interestelar", "matrix", "toy Story","Origen", "Encanto"]

print(peliculas)
print(peliculas[0])
print(peliculas[-1])
print(peliculas[:3])
print(len(peliculas))

print(peliculas[::2])
print(peliculas[1:4])

#Ejercicio 5

carrito = ["pantalon", "Camisa"]

carrito.append("zapatos")
print(carrito)

carrito.insert(1, "cinturon")
print(carrito)

carrito.remove("pantalon")
print(carrito)

print("Camisa" in carrito)

carrito.sort()
print(carrito)

#ejercicio 6

asientos = [
    ["L", "X", "L"],
    ["X", "X", "L"],
    ["L", "L", "X"],
]

print(asientos[0])
print(asientos[1][2])

for fila in asientos:
    print(fila)

#ejercicio 7
ventas_vendedores =[
    ["Marta", 320, 450, 275],
    ["Julio", 180, 200, 210],
]

for vendedor in ventas_vendedores:
  nombre = vendedor[0]
  ventas = vendedor[1:]
  total = sum(ventas)
  print(f"{nombre}: total de ventas ${total}")

#ejercico 8

color = (120, 200, 50)
print (color)
print(color[0], color[1], color[2])
print(type(color))

color_a = (120, 200, 50)
color_b = (10, 10, 10)

def calcular_brillo(c):
  return sum(c)/ 3

brillo_a = calcular_brillo(color_a)
brillo_b = calcular_brillo(color_b)
print(f"Brillo A:{round(brillo_a, 2)}")
print(f"Brillo B:{round(brillo_b, 2)}")

if brillo_a > brillo_b:
  print("El color A es más brillante")
else:
  print("El color B es más brillante")

# Lista de equipos con sus nombres y 3 puntajes de ronda
equipos = [
    ["Los Rayos", 15, 20, 18],
    ["Los Truenos", 12, 15, 10],
    ["Los Relámpagos", 25, 20, 19],
    ["Las Nubes", 8, 10, 7]
]

def clasificar_equipo(total):
  """Clasifica un equipo según su puntaje total."""
  if total >= 60:
    return "Campeón"
  elif total >= 40:
    return "Finalista"
  else:
    return "Participante"

max_puntos = -1
equipo_campeon = None
rondas_bonus_necesarias = 0

print("--- Resultados por Equipo ---")
for equipo in equipos:
  nombre = equipo[0]
  puntajes = equipo[1:]
  total_equipo = sum(puntajes)
  clasificacion = clasificar_equipo(total_equipo)

  print(f"{nombre}: Total = {total_equipo}, Clasificación = {clasificacion}")

  # Encontrar el equipo con el total más alto
  if total_equipo > max_puntos:
    max_puntos = total_equipo
    equipo_campeon = {"nombre": nombre, "total": total_equipo, "clasificacion": clasificacion}

print("\n--- Equipo con el total más alto ---")
print(f"El equipo con el puntaje más alto es: {equipo_campeon['nombre']} con {equipo_campeon['total']} puntos.")

# Simular ronda bonus
if equipo_campeon:
  total_post_bonus = equipo_campeon["total"]
  while total_post_bonus < 70:
    total_post_bonus += 5
    rondas_bonus_necesarias += 1

  print("\n--- Ronda Bonus ---")
  print(f"Equipo: {equipo_campeon['nombre']}")
  print(f"Rondas bonus necesarias: {rondas_bonus_necesarias}")
  print(f"Total final después de la ronda bonus: {total_post_bonus}")

  # Guardar el resultado del campeonato en una tupla
  clasificacion_final_campeon = clasificar_equipo(total_post_bonus)
  resultado_campeonato = (equipo_campeon['nombre'], clasificacion_final_campeon)

  print("\n--- Resultado del Campeonato ---")
  print(f"Equipo Ganador: {resultado_campeonato}")